version: "3.6"

services:
  volumes-populator:
    build: ${DOCKERFILE_PATH}
    volumes:
      - atlas-data-bioentity-properties:/atlas-data/bioentity_properties
      - atlas-data-exp:/atlas-data/exp
      - atlas-data-ontology:/atlas-data/ontology
    command:
      - |
        lftp -e \
        "mirror -vvv /pub/databases/microarray/data/atlas/bioentity_properties /atlas-data/bioentity_properties; exit" \
        ftp.ebi.ac.uk

        # Create a directory for MAGETAB files
        mkdir -p /atlas-data/exp/magetab
        for EXP_ID in ${EXP_IDS}
        do
          lftp -e \
          "mirror -vvv /pub/databases/microarray/data/atlas/experiments/$${EXP_ID} /atlas-data/exp/magetab/$${EXP_ID}; exit" \
          ftp.ebi.ac.uk
        done

volumes:
  atlas-data-bioentity-properties:
    name: ${PROJECT_NAME}_${ATLAS_DATA_BIOENTITY_PROPERTIES_VOL_NAME}
  atlas-data-exp:
    name: ${PROJECT_NAME}_${ATLAS_DATA_EXP_VOL_NAME}
  atlas-data-ontology:
    name: ${PROJECT_NAME}_${ATLAS_DATA_ONTOLOGY_VOL_NAME}
