apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins-gene-expression
spec:
  serviceAccountName: admin-jenkins-gene-expression
  securityContext:
    fsGroup: 1000
  containers:
    - name: jnlp
      resources:
        requests:
          memory: "512Mi"
        limits:
          memory: "512Mi"
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command: ["/busybox/cat"]
      tty: true
      resources:
        requests:
          memory: "1Gi"
        limits:
          memory: "2Gi"
