apiVersion: v1
kind: Pod
metadata:
  namespace: gxa-jenkins
spec:
  serviceAccountName: jenkins-cloud
  # If we set workspaceVolume dynamicPVC() or workspaceVolume persistentVolumeClaimWorkspaceVolume() we need to add a
  # fsGroup 1000 to make the /home/jenkins/agent directory writable. Otherwise, we get the following exception in the
  # jnlp container:
  # Exception in thread "main" java.io.IOException: The specified working directory should be fully accessible to the remoting executable (RWX): /home/jenkins/agent
  # The securityContext in the pod is inherited, as it becomes the default pod template
  securityContext:
    fsGroup: 1000
  initContainers:
    - name: init-experiments-snapshot
      image: busybox
      securityContext:
        runAsUser: 2921
        runAsGroup: 1146
      command: ["sh"]
      args:
        - "-c"
        - |
          set -e
          EXPERIMENTS_SOURCE_DIR="/atlas-data/gxa_codon/.snapshot/gxa_codon_2025-10-14_13:34/experiments"
          if [ ! -d "$EXPERIMENTS_SOURCE_DIR" ]; then
            echo "ERROR: experimentsSourceDir does not exist: $EXPERIMENTS_SOURCE_DIR" >&2
            exit 1
          fi
          ln -s "$EXPERIMENTS_SOURCE_DIR"/E-* /experiments_snapshot/
          echo "Number of experiments in snapshot: $(ls /experiments_snapshot | wc -l)"
      volumeMounts:
        - name: codon-volume
          mountPath: /atlas-data/gxa_codon
        - name: services-volume
          mountPath: /atlas-data/services
        - name: experiments-snapshot
          mountPath: /experiments_snapshot
  containers:
    - name: jnlp
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "512Mi"
          cpu: "500m"
    - name: openjdk
      image: eclipse-temurin:11
      securityContext:
        runAsUser: 2921
        runAsGroup: 1146
      resources:
        requests:
          memory: "2.5Gi"
          cpu: "1"
          ephemeral-storage: "4Gi"
        limits:
          cpu: "4"
          memory: "4Gi"
      env:
      - name: GRADLE_OPTS
        value: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=4"
      command: [ "/bin/sh" ]
      args: [ "-c", "mkdir -p /tmp/expdesign-rw && cp /test-data/expdesign/* /tmp/expdesign-rw/ ; sleep 2h" ]
      volumeMounts:
        - mountPath: /test-data/gxa/magetab
          name: experiments-snapshot
          readOnly: true
        - mountPath: /atlas-data/gxa_codon
          name: codon-volume
          readOnly: true
        - mountPath: /test-data/expdesign
          name: services-volume
          subPath: fg/atlas/environments/ci/expdesign
          readOnly: true
        - mountPath: /test-data/ontology
          name: services-volume
          subPath: fg/atlas/ontology
          readOnly: true
        - mountPath: /test-data/bioentity_properties
          name: services-volume
          subPath: fg/atlas/bioentity_properties/gxa
          readOnly: true
    - name: postgres
      image: postgres:16-alpine
      resources:
        requests:
          memory: "100Mi"
        limits:
          memory: "200Mi"
      env:
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command: ["/busybox/cat"]
      tty: true
      resources:
        requests:
          memory: "1Gi"
        limits:
          memory: "2Gi"
  volumes:
    - name: experiments-snapshot
      emptyDir: {}
    - name: codon-volume
      nfs:
        server: hh-isi-srv-vlan1496.ebi.ac.uk
        path: /ifs/public/ro/gxa_codon
    - name: services-volume
      nfs:
        server: hh-isi-srv-vlan1496.ebi.ac.uk
        path: /ifs/public/services
