version: "3.6"

services:
  gxa-gradle-build:
    extends:
      service: gxa-gradle
      file: docker-compose-gradle.yml
    command: ["sh", "-c", "gradle clean :app:war"]

  gxa-gradle-shell:
    extends:
      service: gxa-gradle
      file: docker-compose-gradle.yml
    tty: true
    stdin_open: true
    command: [ "sh", "-c", "gradle && /bin/bash" ]
    depends_on:
      gxa-gradle-build:
        condition: service_completed_successfully

  gxa-tomcat:
    extends:
      service: gxa-tomcat
      file: docker-compose-tomcat.yml
    depends_on:
      gxa-gradle-build:
        condition: service_completed_successfully
      gxa-postgres:
        condition: service_started
      gxa-solrcloud-0:
        condition: service_started
      gxa-solrcloud-1:
        condition: service_started