version: "3.6"

services:
  gxa-gradle:
    image: openjdk:11
    container_name: gxa-gradle
    networks:
      - gxa
    ports:
      - "5005:5005"
    working_dir: /root/project
    volumes:
      - ..:/root/project
      - ./packages:/root/.m2
      - $ATLAS_DATA_PATH:/root/gxa/integration-test-data
    depends_on:
      - gxa-solrcloud-1
      - gxa-solrcloud-2
      - gxa-flyway-test
    environment:
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    command:
      - sh
      - -c
      - >
        ./gradlew :app:clean &&
        ./gradlew
        -PdataFilesLocation=/root/gxa/integration-test-data
        -PexperimentFilesLocation=/root/gxa/integration-test-data/gxa
        -PjdbcUrl=jdbc:postgresql://$POSTGRES_HOST:5432/$POSTGRES_DB
        -PjdbcUsername=$POSTGRES_USER
        -PjdbcPassword=$POSTGRES_PASSWORD
        -PzkHost=gxa-zk-1
        -PsolrHost=gxa-solrcloud-1
        :app:testClasses &&
        ./gradlew -PtestResultsPath=ut :app:test --tests *Test &&
        ./gradlew -PtestResultsPath=it -PexcludeTests=**/*WIT.class :app:test --tests *IT &&
        ./gradlew -PtestResultsPath=e2e :app:test --tests *WIT &&
        ./gradlew :app:jacocoTestReport
networks:
  gxa:
    name: gxa