version: "3.6"

services:
  gxa-gradle-build:
    extends:
      service: gxa-gradle
      file: docker-compose-gradle.yml
    ports:
      - "5005:5005"
    command: ["sh", "-c", "gradle clean :app:war"]

  gxa-gradle-shell:
    extends:
      service: gxa-gradle
      file: docker-compose-gradle.yml
    tty: true
    stdin_open: true
    command: [ "sh", "-c", "gradle && /bin/bash" ]
    depends_on:
      gxa-gradle-build:
        condition: service_completed_successfully
    ports:
      - "5006:5005"
