version: "3.6"

services:
  gxa-postgres-test:
    image: postgres:10-alpine
    container_name: $POSTGRES_HOST
    networks:
      - gxa
    restart: always
    command: -c max_wal_size=2GB
    environment:
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "5432:5432"

  gxa-flyway-test:
    image: flyway/flyway
    container_name: gxa-flyway-test
    networks:
      - gxa
    command: -url=jdbc:postgresql://$POSTGRES_HOST/$POSTGRES_DB -schemas=$POSTGRES_USER -user=$POSTGRES_USER -password=$POSTGRES_PASSWORD -connectRetries=60 migrate
    volumes:
      - ../schemas/flyway/gxa/:/flyway/sql
    depends_on:
      - gxa-postgres-test

networks:
  gxa:
    name: gxa
