version: "3.6"

services:
  gxa-tomcat:
    image: tomcat:9-jdk11
    container_name: gxa-tomcat
    networks:
      - atlas-test-net
    environment:
      JPDA_ADDRESS: "*:8000"
      JAVA_OPTS: "-Dsolr.httpclient.builder.factory=org.apache.solr.client.solrj.impl.PreemptiveBasicAuthClientBuilderFactory -Dbasicauth=${SOLR_USER}:${SOLR_PASSWORD}"
    ports:
      - "8080:8080"
      - "8000:8000"
    volumes:
      - ../webapps:/usr/local/tomcat/webapps
      - ./webapp-properties:/webapp-properties
      - bioentity-properties:/atlas-data/bioentity_properties
      - gxa-data:/atlas-data/exp
      - gxa-expdesign:/atlas-data/expdesign
      - gxa-exp:/atlas-data/exp
      - gxa-tomcat-conf:/usr/local/tomcat/conf
    depends_on:
      gxa-gradle-build:
        condition: service_completed_successfully
      gxa-postgres:
        condition: service_started
      gxa-solrcloud-0:
        condition: service_started
      gxa-solrcloud-1:
        condition: service_started
    command: ["catalina.sh", "jpda", "run"]

volumes:
  gradle-wrapper-dists:
    name: ${PROJECT_NAME:?err}_${GRADLE_WRAPPER_DISTS_VOL_NAME}
  gradle-ro-dep-cache:
    name: ${PROJECT_NAME}_${GRADLE_RO_DEP_CACHE_VOL_NAME}
  gxa-data:
    name: ${PROJECT_NAME}_${ATLAS_DATA_VOL_NAME}
  gxa-tomcat-conf:
    name: gxa-tomcat-conf
  bioentity-properties:
    name: ${PROJECT_NAME}_${ATLAS_DATA_BIOENTITY_PROPERTIES_VOL_NAME}
  gxa-exp:
    name: ${PROJECT_NAME}_${ATLAS_DATA_EXP_VOL_NAME}
  gxa-expdesign:
    name: ${PROJECT_NAME}_${ATLAS_DATA_EXPDESIGN_VOL_NAME}

networks:
  atlas-test-net:
    name: atlas-test-net