version: "3.6"

services:
  gxa-postgres:
    container_name: ${POSTGRES_HOST}
    image: postgres:11-alpine
    networks:
      - atlas-test-net
    restart: always
    command: -c max_wal_size=2GB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB

  gxa-flyway:
    image: flyway/flyway
    networks:
      - atlas-test-net
    command: [
      "-url=jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DB}",
      "-schemas=${POSTGRES_USER}",
      "-user=${POSTGRES_USER}",
      "-password=${POSTGRES_PASSWORD}",
      "-connectRetries=60",
      "migrate"
    ]
    volumes:
      - ../schemas/flyway/gxa/:/flyway/sql
    depends_on:
      - gxa-postgres

volumes:
  pgdata:
    name: ${PROJECT_NAME:?err}_pgdata

networks:
  atlas-test-net:
    name: atlas-test-net