version: "3.6"

services:
  postgres-test:
    image: postgres:11-alpine
    container_name: ${POSTGRES_HOST}
    networks:
      - atlas-test-net
    restart: always
    command: -c max_wal_size=1GB
    ports:
      - "5432:5432"

  flyway:
    image: flyway/flyway
    networks:
      - atlas-test-net
    command: [
      "-url=jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DB}",
      "-schemas=${POSTGRES_USER}",
      "-user=${POSTGRES_USER}",
      "-password=${POSTGRES_PASSWORD}",
      "-connectRetries=60",
      "migrate"
    ]
    volumes:
      - ../schemas/flyway/gxa/:/flyway/sql
    depends_on:
      - gxa-postgres-test

networks:
  atlas-test-net:
    name: atlas-test-net
