version: "3.6"

services:
  gxa-gradle-build:
    extends:
      service: gxa-gradle
      file: docker-compose-gradle.yml
    ports:
      - "5005:5005"

  gxa-gradle-shell:
    extends:
      service: gxa-gradle
      file: docker-compose-gradle.yml
    networks:
      - atlas-test-net
    ports:
      - "5006:5005"
    tty: true
    stdin_open: true
    command: [ "sh", "-c", "gradle && /bin/bash" ]