version: "3.6"

services:
  gxa-zk-1:
    image: zookeeper:3.4.14
    container_name: gxa-zk-1
    networks:
      - gxa
    ports:
      - "2181:2181"
    restart: always
    volumes:
      - gxa-zk-1-data:/data
      - gxa-zk-1-datalog:/datalog
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=gxa-zk-2:2888:3888 server.3=gxa-zk-3:2888:3888

  gxa-zk-2:
    image: zookeeper:3.4.14
    container_name: gxa-zk-2
    networks:
      - gxa
    ports:
      - "2182:2181"
    restart: always
    volumes:
      - gxa-zk-2-data:/data
      - gxa-zk-2-datalog:/datalog
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=gxa-zk-1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=gxa-zk-3:2888:3888

  gxa-zk-3:
    image: zookeeper:3.4.14
    container_name: gxa-zk-3
    networks:
      - gxa
    ports:
      - "2183:2181"
    restart: always
    volumes:
      - gxa-zk-3-data:/data
      - gxa-zk-3-datalog:/datalog
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=gxa-zk-1:2888:3888 server.2=gxa-zk-2:2888:3888 server.3=0.0.0.0:2888:3888

  gxa-solrcloud-1:
    image: solr:7.1.0
    container_name: gxa-solrcloud-1
    networks:
      - gxa
    ports:
      - "8983:8983"
    volumes:
      - gxa-solrcloud-1-data:/opt/solr/server/solr
      - $ATLAS_DATA_PATH/solrcloud/solr1:/var/backups/solr
    environment:
      - SOLR_HEAP=2g
      - SOLR_OPTS=-Denable.runtime.lib=true
      - ZK_HOST=gxa-zk-1:2181,gxa-zk-2:2181,gxa-zk-3:2181
    depends_on:
      - gxa-zk-1
      - gxa-zk-2
      - gxa-zk-3

  gxa-solrcloud-2:
    image: solr:7.1.0
    container_name: gxa-solrcloud-2
    networks:
      - gxa
    ports:
      - "8984:8983"
    volumes:
      - gxa-solrcloud-2-data:/opt/solr/server/solr
      - $ATLAS_DATA_PATH/solrcloud/solr2:/var/backups/solr
    environment:
      - SOLR_HEAP=2g
      - SOLR_OPTS=-Denable.runtime.lib=true
      - ZK_HOST=gxa-zk-1:2181,gxa-zk-2:2181,gxa-zk-3:2181
    depends_on:
      - gxa-zk-1
      - gxa-zk-2
      - gxa-zk-3

volumes:
  gxa-zk-1-data:
    name: gxa-zk-1-data
  gxa-zk-1-datalog:
    name: gxa-zk-1-datalog
  gxa-zk-2-data:
    name: gxa-zk-2-data
  gxa-zk-2-datalog:
    name: gxa-zk-2-datalog
  gxa-zk-3-data:
    name: gxa-zk-3-data
  gxa-zk-3-datalog:
    name: gxa-zk-3-datalog
  gxa-solrcloud-1-data:
    name: gxa-solrcloud-1-data
  gxa-solrcloud-2-data:
    name: gxa-solrcloud-2-data

networks:
  gxa:
    name: gxa