version: "3.6"

services:
  gxa-solrcloud-zookeeper-0:
    container_name: ${SOLR_CLOUD_ZK_CONTAINER_1_NAME}
    image: zookeeper:3.7.0
    networks:
      - atlas-test-net
    ports:
      - 2181:2181
      - 7000:7000
    volumes:
      - gxa-solrcloud-zookeeper-0-data:/data
      - gxa-solrcloud-zookeeper-0-datalog:/datalog
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=${SOLR_CLOUD_ZK_CONTAINER_1_NAME}:2888:3888;2181 server.2=${SOLR_CLOUD_ZK_CONTAINER_2_NAME}:2888:3888;2181 server.3=${SOLR_CLOUD_ZK_CONTAINER_3_NAME}:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ZOO_CFG_EXTRA: metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true

  gxa-solrcloud-zookeeper-1:
    container_name: ${SOLR_CLOUD_ZK_CONTAINER_2_NAME}
    image: zookeeper:3.7.0
    networks:
      - atlas-test-net
    ports:
      - 2182:2181
      - 7001:7000
    volumes:
      - gxa-solrcloud-zookeeper-1-data:/data
      - gxa-solrcloud-zookeeper-1-datalog:/datalog
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=${SOLR_CLOUD_ZK_CONTAINER_1_NAME}:2888:3888;2181 server.2=${SOLR_CLOUD_ZK_CONTAINER_2_NAME}:2888:3888;2181 server.3=${SOLR_CLOUD_ZK_CONTAINER_3_NAME}:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ZOO_CFG_EXTRA: metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true

  gxa-solrcloud-zookeeper-2:
    container_name: ${SOLR_CLOUD_ZK_CONTAINER_3_NAME}
    image: zookeeper:3.7.0
    networks:
      - atlas-test-net
    ports:
      - 2183:2181
      - 7002:7000
    volumes:
      - gxa-solrcloud-zookeeper-2-data:/data
      - gxa-solrcloud-zookeeper-2-datalog:/datalog
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=${SOLR_CLOUD_ZK_CONTAINER_1_NAME}:2888:3888;2181 server.2=${SOLR_CLOUD_ZK_CONTAINER_2_NAME}:2888:3888;2181 server.3=${SOLR_CLOUD_ZK_CONTAINER_3_NAME}:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ZOO_CFG_EXTRA: metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true

  gxa-solrcloud-0:
    container_name: ${SOLR_CLOUD_CONTAINER_1_NAME}
    image: solr:8.7.0
    networks:
      - atlas-test-net
    ports:
      - 8983:8983
    volumes:
      - gxa-solrcloud-0-data:/var/solr/data
    environment:
      SOLR_JAVA_STACK_SIZE: '-Xss512k'
      SOLR_HEAP: 3g
      SOLR_OPTS: -Denable.packages=true -Dsolr.max.booleanClauses=100000000
      ZK_HOST: ${SOLR_CLOUD_ZK_CONTAINER_1_NAME}:2181,${SOLR_CLOUD_ZK_CONTAINER_2_NAME}:2181,${SOLR_CLOUD_ZK_CONTAINER_3_NAME}:2181
    depends_on:
      - gxa-solrcloud-zookeeper-0
      - gxa-solrcloud-zookeeper-1
      - gxa-solrcloud-zookeeper-2

  gxa-solrcloud-1:
    container_name: ${SOLR_CLOUD_CONTAINER_2_NAME}
    image: solr:8.7.0
    networks:
      - atlas-test-net
    ports:
      - 8984:8983
    volumes:
      - gxa-solrcloud-1-data:/var/solr/data
    environment:
      SOLR_JAVA_STACK_SIZE: '-Xss512k'
      SOLR_HEAP: 3g
      SOLR_OPTS: -Denable.packages=true -Dsolr.max.booleanClauses=100000000
      ZK_HOST: ${SOLR_CLOUD_ZK_CONTAINER_1_NAME}:2181,${SOLR_CLOUD_ZK_CONTAINER_2_NAME}:2181,${SOLR_CLOUD_ZK_CONTAINER_3_NAME}:2181
    depends_on:
      - gxa-solrcloud-zookeeper-0
      - gxa-solrcloud-zookeeper-1
      - gxa-solrcloud-zookeeper-2

volumes:
  gxa-solrcloud-zookeeper-0-data:
    name: gxa-solrcloud-zookeeper-0-data
  gxa-solrcloud-zookeeper-0-datalog:
    name: gxa-solrcloud-zookeeper-0-datalog
  gxa-solrcloud-zookeeper-1-data:
    name: gxa-solrcloud-zookeeper-1-data
  gxa-solrcloud-zookeeper-1-datalog:
    name: gxa-solrcloud-zookeeper-1-datalog
  gxa-solrcloud-zookeeper-2-data:
    name: gxa-solrcloud-zookeeper-2-data
  gxa-solrcloud-zookeeper-2-datalog:
    name: gxa-solrcloud-zookeeper-2-datalog
  gxa-solrcloud-0-data:
    name: gxa-solrcloud-0-data
  gxa-solrcloud-1-data:
    name: gxa-solrcloud-1-data

networks:
  atlas-test-net:
    name: atlas-test-net