plugins {
    id 'atlas-web-app.java-conventions'
    id 'war'
    id 'org.flywaydb.flyway' version '7.14.0'
    id "com.gorylenko.gradle-git-properties" version "2.4.1"
    id "io.spring.dependency-management" version "1.0.6.RELEASE"
}

dependencyManagement {
    imports {
        mavenBom 'org.springframework.security:spring-security-bom:5.1.5.RELEASE'
        mavenBom 'org.springframework:spring-framework-bom:5.1.6.RELEASE'
    }
}

gitProperties {
    gitPropertiesName = "resources/git.properties"
}

war {
    // Let’s clean the exploded WAR if it’s there
    def destinationPath = '../webapps'
    def artifactName = 'gxa'
    doFirst {
        delete "${destinationPath}/${artifactName}"
    }

    archiveFileName = "${artifactName}.war"
    destinationDirectory = file "${destinationPath}"
}

dependencies {
    implementation project(':atlas-web-core')

    implementation 'org.springframework:spring-context'
    implementation 'org.springframework:spring-web'
    implementation 'org.springframework:spring-jdbc'
    implementation 'org.springframework:spring-webmvc'

    implementation "org.springframework.security:spring-security-web"
    implementation "org.springframework.security:spring-security-config"

    implementation 'javax.validation:validation-api:2.0.1.Final'
    implementation 'commons-net:commons-net:3.8.0'

    implementation 'org.springframework:spring-context-support'
    implementation 'org.springframework.data:spring-data-redis:2.4.3'
    implementation 'redis.clients:jedis:3.3.0'

    implementation 'org.thymeleaf:thymeleaf:3.1.2.RELEASE'
    implementation 'org.thymeleaf:thymeleaf-spring5:3.1.2.RELEASE'

    // For URL rewrite (see WEB-INF/web.xml), or your Filter will fail with the most confusing error messages
    runtimeOnly 'org.tuckey:urlrewritefilter:4.0.3'

    testImplementation 'commons-beanutils:commons-beanutils:1.9.3'

    testImplementation 'com.zaxxer:HikariCP:3.3.1'
}
