data.files.location = /atlas-data
experiment.files.location = /atlas-data/exp
experiment.design.location = /atlas-data/expdesign

build.number = 42
build.branch = development
build.commitId = development
build.tomcatHostname = localhost@docker

ensembl.rest.base.url = https://rest.ensembl.org
ensembl.cache.entry.capacity = 50000
ensembl.cache.stats.log.interval.ms = 3600000
