name: Build atlas-web-bulk WAR
on:
  pull_request

jobs:
  compile_war:
    name: compile_war
    strategy:
      fail-fast: false #  if one of the jobs in the matrix expansion fails, the rest of the jobs will be cancelled
      matrix:
        os: ["ubuntu-latest"]
        jdk: [11]
    runs-on: ${{ matrix.os }}
    env:
      JDK_VERSION: ${{ matrix.jdk }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Bulid WAR
        run: ./gradlew --no-daemon :app:war
      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: gxa-war
          path: webapps/*.war
          retention-days: 7  # Set how many days to retain the artifact (1–90)
